version: '3.7'

services:
  app:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app:/app/
      - staticfiles:/app/static/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  web:
    build: ./web
    volumes:
      - ./web:/app/
    expose:
      - 3000

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hello

  nginx:
    build: ./nginx
    volumes:
      - staticfiles:/app/static/
      - ./web/public:/app/
    ports:
      - 8008:80
    depends_on:
      - web
      - app

volumes:
  postgres_data:
  staticfiles:
